Updates to extend the core recommendations for 1.2.
json-ld/json-ld-wg-charter pull request #6
Opened 2024-09-07 21:16 UTC by gkellogg

FPWD dates are out from YAML-LD and CBOR-LD, as is REC dates; those other dates may need to be updated to reference the JSON-LD 1.2 versions.

2024-09-09 17:23 UTC, TallTed requested changes

2024-09-09 17:23 UTC, TallTed commented on 2024/json-ld-wg/index.html
> +            The Working Group will deliver the following W3C normative specifications specifications:
```suggestion
            The Working Group will deliver the following W3C normative specifications:
```

2024-09-09 17:23 UTC, TallTed commented on 2024/json-ld-wg/index.html
> +          as noted on the groups <a href="https://github.com/orgs/w3c/projects/84">Project Management Page</a>.
This may need to be specific and/or refer to a static page, rather than a dynamically updated page.

2024-09-10 14:59 UTC, BigBlueHat approved these changes

2024-09-30 23:15 UTC, merged